### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by SnakeByteIL** [technoskald/maltrieve#66]
IOError: [Errno 24] Too many open files: 'urls.json

It seems that the process is running too many simultaneous file downloads? 
This can be fixed with extending /etc/security/limits.conf to 5000 current is:
$ ulimit -n = 1000 
maybe queuing system or making sure files are closed after download?

**Comment by dray0n** [comment]
I was having the same issues on a fresh install. I was able to remedy the issue:

$ ulimit -a 
open files     (-n) 1024

$ ulimit -n 2048

Maltrieve has now been running for 30 minutes without an issue.  Before, I was erroring out after about 5-10 minutes of running.

**Comment by technoskald** [comment]
Can one of you who's experienced the issue test the `rlimit` branch? It implements the fix suggested by @alienone with a limit of 2048 descriptors as @dray0n is using.

**Comment by dray0n** [comment]
I am going to load the rlimit branch right now.... but as a note I received the error again. Roughly 45-minutes in.

**Comment by technoskald** [comment]
This is so odd because the Python context manager (`with`) should close the file when exiting that block. It makes me wonder if grequests is holding something open.

**Comment by dray0n** [comment]
$  netstat -an 

Hundreds of "CLOSE_WAIT"'s out there.

**Comment by dray0n** [comment]
Been awhile...  I was going through the dependencies and found out that I did not have all of the requirements met for some reason.   Problem solved through a few issues on missing packages and was finally able to get all requirements met.

Open socket issue is no longer an issue.

**Comment by SnakeByteIL** [comment]
cheers

**Comment by technoskald** [comment]
:+1:

**Comment by jebelingmi** [comment]
just got same issue reported above on fresh install today.
jeff@ubuntu64:~/maltrieve$  python /home/jeff/maltrieve/maltrieve.py -l logfile.txt -p http://192.168.11.122:9090 -d /home/jeff/maltrieve/malware/              External sites see 68.40.253.188

Processing source URLs
Completed source processing
Downloading samples, check log for details
Traceback (most recent call last):
  File "/home/jeff/maltrieve/maltrieve.py", line 514, in <module>
  File "/home/jeff/maltrieve/maltrieve.py", line 503, in main
  File "/home/jeff/maltrieve/maltrieve.py", line 340, in save_malware
IOError: [Errno 24] Too many open files: '/home/jeff/maltrieve/malware/bbc0dacb709608260751692405972b7b'
